// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movieArchieve.Data;

#nullable disable

namespace movieArchieve.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420162601_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("movieArchieve.Entities.Actor", b =>
                {
                    b.Property<int>("actorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("actorID"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("actorID");

                    b.ToTable("actor");
                });

            modelBuilder.Entity("movieArchieve.Entities.Director", b =>
                {
                    b.Property<int>("directorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("directorID"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("rating")
                        .HasColumnType("double");

                    b.HasKey("directorID");

                    b.ToTable("director");
                });

            modelBuilder.Entity("movieArchieve.Entities.Genre", b =>
                {
                    b.Property<int>("genreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("genreID"));

                    b.Property<string>("genreName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("movieGenresID")
                        .HasColumnType("int");

                    b.HasKey("genreID");

                    b.ToTable("genre");
                });

            modelBuilder.Entity("movieArchieve.Entities.Movie", b =>
                {
                    b.Property<int>("movieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("movieID"));

                    b.Property<int?>("directorID")
                        .HasColumnType("int");

                    b.Property<int?>("languageID")
                        .HasColumnType("int");

                    b.Property<string>("overview")
                        .HasColumnType("longtext");

                    b.Property<double?>("rating")
                        .HasColumnType("double");

                    b.Property<DateTime?>("releaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("runtimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("movieID");

                    b.HasIndex("directorID");

                    b.HasIndex("languageID");

                    b.ToTable("movie");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieActor", b =>
                {
                    b.Property<int>("movieID")
                        .HasColumnType("int");

                    b.Property<int>("actorID")
                        .HasColumnType("int");

                    b.Property<string>("charName")
                        .HasColumnType("longtext");

                    b.HasKey("movieID", "actorID");

                    b.HasIndex("actorID");

                    b.ToTable("movieActor");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieGenre", b =>
                {
                    b.Property<int>("movieID")
                        .HasColumnType("int");

                    b.Property<int>("genreID")
                        .HasColumnType("int");

                    b.Property<int?>("Genre")
                        .HasColumnType("int");

                    b.Property<int?>("Movie")
                        .HasColumnType("int");

                    b.HasKey("movieID", "genreID");

                    b.HasIndex("Genre");

                    b.HasIndex("Movie");

                    b.ToTable("movieGenre");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieLang", b =>
                {
                    b.Property<int>("languageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("languageID"));

                    b.Property<string>("langName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("languageID");

                    b.ToTable("movieLang");
                });

            modelBuilder.Entity("movieArchieve.Entities.Rating", b =>
                {
                    b.Property<int>("ratingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ratingID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("movieID")
                        .HasColumnType("int");

                    b.Property<double>("score")
                        .HasColumnType("double");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("ratingID");

                    b.HasIndex("movieID");

                    b.HasIndex("userID");

                    b.ToTable("rating");
                });

            modelBuilder.Entity("movieArchieve.Entities.Review", b =>
                {
                    b.Property<int>("reviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("reviewID"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("movieID")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("reviewID");

                    b.HasIndex("movieID");

                    b.HasIndex("userID");

                    b.ToTable("review");
                });

            modelBuilder.Entity("movieArchieve.Entities.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("userID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("userID");

                    b.ToTable("user");
                });

            modelBuilder.Entity("movieArchieve.Entities.Watchlist", b =>
                {
                    b.Property<int>("watchlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("watchlistID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("listName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("watchlistID");

                    b.HasIndex("userID");

                    b.ToTable("watchlist");
                });

            modelBuilder.Entity("movieArchieve.Entities.WatchlistMovie", b =>
                {
                    b.Property<int>("watchlistID")
                        .HasColumnType("int");

                    b.Property<int>("movieID")
                        .HasColumnType("int");

                    b.HasKey("watchlistID", "movieID");

                    b.HasIndex("movieID");

                    b.ToTable("watchlistMovie");
                });

            modelBuilder.Entity("movieArchieve.Entities.Movie", b =>
                {
                    b.HasOne("movieArchieve.Entities.Director", "Director")
                        .WithMany()
                        .HasForeignKey("directorID");

                    b.HasOne("movieArchieve.Entities.MovieLang", "Language")
                        .WithMany("Movies")
                        .HasForeignKey("languageID");

                    b.Navigation("Director");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieActor", b =>
                {
                    b.HasOne("movieArchieve.Entities.Actor", "actor")
                        .WithMany()
                        .HasForeignKey("actorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movieArchieve.Entities.Movie", "movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("movieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actor");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieGenre", b =>
                {
                    b.HasOne("movieArchieve.Entities.Genre", "genre")
                        .WithMany()
                        .HasForeignKey("Genre");

                    b.HasOne("movieArchieve.Entities.Movie", "movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("Movie");

                    b.Navigation("genre");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("movieArchieve.Entities.Rating", b =>
                {
                    b.HasOne("movieArchieve.Entities.Movie", "movie")
                        .WithMany("Ratings")
                        .HasForeignKey("movieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movieArchieve.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie");

                    b.Navigation("user");
                });

            modelBuilder.Entity("movieArchieve.Entities.Review", b =>
                {
                    b.HasOne("movieArchieve.Entities.Movie", "movie")
                        .WithMany("Reviews")
                        .HasForeignKey("movieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movieArchieve.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie");

                    b.Navigation("user");
                });

            modelBuilder.Entity("movieArchieve.Entities.Watchlist", b =>
                {
                    b.HasOne("movieArchieve.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("movieArchieve.Entities.WatchlistMovie", b =>
                {
                    b.HasOne("movieArchieve.Entities.Movie", "movie")
                        .WithMany("WatchlistMovies")
                        .HasForeignKey("movieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movieArchieve.Entities.Watchlist", "watchlist")
                        .WithMany()
                        .HasForeignKey("watchlistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie");

                    b.Navigation("watchlist");
                });

            modelBuilder.Entity("movieArchieve.Entities.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieGenres");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");

                    b.Navigation("WatchlistMovies");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieLang", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
