// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movieArchieve.Data;

#nullable disable

namespace movieArchieve.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410162056_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("movieArchieve.Entities.Actors", b =>
                {
                    b.Property<int>("actorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("actorID"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("actorID");

                    b.ToTable("actors");
                });

            modelBuilder.Entity("movieArchieve.Entities.Directors", b =>
                {
                    b.Property<int>("directorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("directorID"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("rating")
                        .HasColumnType("double");

                    b.HasKey("directorID");

                    b.ToTable("directors");
                });

            modelBuilder.Entity("movieArchieve.Entities.Genres", b =>
                {
                    b.Property<int>("genreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("genreID"));

                    b.Property<string>("genreName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("movieGenresID")
                        .HasColumnType("int");

                    b.HasKey("genreID");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieActors", b =>
                {
                    b.Property<int>("movieID")
                        .HasColumnType("int");

                    b.Property<int>("actorID")
                        .HasColumnType("int");

                    b.Property<int?>("actors")
                        .HasColumnType("int");

                    b.Property<string>("charName")
                        .HasColumnType("longtext");

                    b.Property<int?>("movies")
                        .HasColumnType("int");

                    b.HasKey("movieID", "actorID");

                    b.HasIndex("actors");

                    b.HasIndex("movies");

                    b.ToTable("movieActors");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieGenres", b =>
                {
                    b.Property<int>("movieID")
                        .HasColumnType("int");

                    b.Property<int>("genreID")
                        .HasColumnType("int");

                    b.Property<int?>("Genre")
                        .HasColumnType("int");

                    b.Property<int?>("Movie")
                        .HasColumnType("int");

                    b.HasKey("movieID", "genreID");

                    b.HasIndex("Genre");

                    b.HasIndex("Movie");

                    b.ToTable("movieGenres");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieLangs", b =>
                {
                    b.Property<int>("languageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("languageID"));

                    b.Property<string>("langName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("languageID");

                    b.ToTable("movieLangs");
                });

            modelBuilder.Entity("movieArchieve.Entities.Movies", b =>
                {
                    b.Property<int>("movieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("movieID"));

                    b.Property<int?>("movie_director")
                        .HasColumnType("int");

                    b.Property<int?>("movie_languages")
                        .HasColumnType("int");

                    b.Property<string>("overview")
                        .HasColumnType("longtext");

                    b.Property<double?>("rating")
                        .HasColumnType("double");

                    b.Property<DateTime?>("releaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("runtimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("movieID");

                    b.HasIndex("movie_director");

                    b.HasIndex("movie_languages");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("movieArchieve.Entities.Ratings", b =>
                {
                    b.Property<int>("ratingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ratingID"));

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("scor")
                        .HasColumnType("double");

                    b.HasKey("ratingID");

                    b.HasIndex("MovieID");

                    b.HasIndex("UserID");

                    b.ToTable("ratings");
                });

            modelBuilder.Entity("movieArchieve.Entities.Reviews", b =>
                {
                    b.Property<int>("reviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("reviewID"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("review_movie")
                        .HasColumnType("int");

                    b.Property<int?>("review_user")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("reviewID");

                    b.HasIndex("review_movie");

                    b.HasIndex("review_user");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("movieArchieve.Entities.Users", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("userID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("userID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("movieArchieve.Entities.WatchlistMovies", b =>
                {
                    b.Property<int>("watchlistID")
                        .HasColumnType("int");

                    b.Property<int>("movieID")
                        .HasColumnType("int");

                    b.HasKey("watchlistID", "movieID");

                    b.HasIndex("movieID");

                    b.ToTable("watchlistMovies");
                });

            modelBuilder.Entity("movieArchieve.Entities.Watchlists", b =>
                {
                    b.Property<int>("watchlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("watchlistID"));

                    b.Property<int?>("User")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("listName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("watchlistID");

                    b.HasIndex("User");

                    b.ToTable("watchlists");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieActors", b =>
                {
                    b.HasOne("movieArchieve.Entities.Actors", "actor")
                        .WithMany()
                        .HasForeignKey("actors");

                    b.HasOne("movieArchieve.Entities.Movies", "movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("movies");

                    b.Navigation("actor");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieGenres", b =>
                {
                    b.HasOne("movieArchieve.Entities.Genres", "genre")
                        .WithMany()
                        .HasForeignKey("Genre");

                    b.HasOne("movieArchieve.Entities.Movies", "movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("Movie");

                    b.Navigation("genre");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("movieArchieve.Entities.Movies", b =>
                {
                    b.HasOne("movieArchieve.Entities.Directors", "Director")
                        .WithMany()
                        .HasForeignKey("movie_director");

                    b.HasOne("movieArchieve.Entities.MovieLangs", "Language")
                        .WithMany("Movies")
                        .HasForeignKey("movie_languages");

                    b.Navigation("Director");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("movieArchieve.Entities.Ratings", b =>
                {
                    b.HasOne("movieArchieve.Entities.Movies", "movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movieArchieve.Entities.Users", "user")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("movie");

                    b.Navigation("user");
                });

            modelBuilder.Entity("movieArchieve.Entities.Reviews", b =>
                {
                    b.HasOne("movieArchieve.Entities.Movies", "movie")
                        .WithMany("Reviews")
                        .HasForeignKey("review_movie");

                    b.HasOne("movieArchieve.Entities.Users", "user")
                        .WithMany()
                        .HasForeignKey("review_user");

                    b.Navigation("movie");

                    b.Navigation("user");
                });

            modelBuilder.Entity("movieArchieve.Entities.WatchlistMovies", b =>
                {
                    b.HasOne("movieArchieve.Entities.Movies", "movie")
                        .WithMany("WatchlistMovies")
                        .HasForeignKey("movieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movieArchieve.Entities.Watchlists", "watchlist")
                        .WithMany()
                        .HasForeignKey("watchlistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("movie");

                    b.Navigation("watchlist");
                });

            modelBuilder.Entity("movieArchieve.Entities.Watchlists", b =>
                {
                    b.HasOne("movieArchieve.Entities.Users", "userID")
                        .WithMany()
                        .HasForeignKey("User");

                    b.Navigation("userID");
                });

            modelBuilder.Entity("movieArchieve.Entities.MovieLangs", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("movieArchieve.Entities.Movies", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieGenres");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");

                    b.Navigation("WatchlistMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
